<a href="https://colab.research.google.com/github/annala999/Pytorch-Tutorial-Youtube/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.PyTorch Fundamentals

In [54]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


# Introduction to Tensors
## Creating tensors
#### PyTorch tensors are created torch.Tensor()=https:pytorch.org/docs/stable/tensor.html

In [55]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [56]:
scalar.ndim

0

In [57]:
# Get tensor back as Python int
scalar.item()

7

In [58]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [59]:
vector.ndim

1

In [60]:
vector.shape

torch.Size([2])

In [61]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [62]:
MATRIX[1]

tensor([ 9, 10])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [65]:
TENSOR.ndim

3

In [66]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors
### Why random tensors?
#### Random tensor are important because the way many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
##### Start with random numbers -> look at data -> updata random numbers -> look at data -> updata random *numbers*

In [68]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0176, 0.5218, 0.9119, 0.4392],
        [0.1078, 0.3108, 0.3519, 0.0914],
        [0.9520, 0.7697, 0.1828, 0.0912]])

In [69]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,244,244)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [70]:
random_image_size_tensor = torch.rand(size=(244,244,3)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and omes

In [71]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
ones.dtype

torch.float32

## Creating a range of tensors and tensor-like

In [75]:
# Use torch.range() and deprecated message,use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device


In [77]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,   #What datatype is the tensor (e.g. float32 or float16)
                               device=None,  # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [78]:
float_32_tensor.dtype

torch.float32

In [79]:
non_default_tensor = torch.tensor([3.0,6.0,9.0],
                                  dtype=torch.float16)
non_default_tensor,non_default_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [80]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [81]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [82]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor


tensor([3, 6, 9])

In [83]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### Getting information from tensors ( tensor attributes)
1.Tensors not right datatype - to do get datatype from a tensor,can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor,can use tensor.shape

3.Tensors not on the right device - to get device from a tensor,can use tensor.device

In [84]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9591, 0.9939, 0.4145, 0.3649],
        [0.2475, 0.7498, 0.7090, 0.8558],
        [0.1817, 0.9051, 0.5058, 0.7755]])

In [85]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [86]:
some_tensor.size

<function Tensor.size>

In [87]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.9591, 0.9939, 0.4145, 0.3649],
        [0.2475, 0.7498, 0.7090, 0.8558],
        [0.1817, 0.9051, 0.5058, 0.7755]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


## Manipulating Tensors(tensor operations)
Tensor opertions include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [88]:
# Creat a tensor and 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [89]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [90]:
tensor

tensor([1, 2, 3])

In [91]:
# Substract 10
tensor-10

tensor([-9, -8, -7])

In [92]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [93]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:

   1.Element-wise multiplication

   2.Matrix mutliplication(dot product)

   There are two main rules that performing matrix mutliplication needs to satisfy:

   1.The **inner dimension** must match:
   * `(3,2) @  (3,2) ` won't work
   * `(2,3) @  (3,2) ` will work
   * `(3,2) @  (2,3) ` will work
   
   2.The resulting matrix has the shape of the **outer dimensions**
   * (2,3) @ (3,2) -> (2,2)
   * (3,2) @ (2,3) -> (3,3)

In [95]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

In [ ]:

torch.matmul(torch.rand(3,2),torch.rand(2,3))

In [ ]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

In [96]:
tensor

tensor([1, 2, 3])

In [97]:
tensor@tensor

tensor(14)

In [98]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [99]:
%%time
value = 0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 991 µs, sys: 1.02 ms, total: 2.01 ms
Wall time: 2.05 ms


In [100]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 357 µs, sys: 0 ns, total: 357 µs
Wall time: 298 µs


tensor(14)

## One of the most common erris in deep learning:shape errors

In [102]:
# shape for matrix multiplication
tensor_A = torch.tensor(
                        [[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,8],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)
tensor.matmul(tensor_A,tensor_B)

TypeError: matmul() takes 1 positional argument but 2 were given

In [ ]:
tensor_A.shape,tensor_B.shape

###### To fixour tensor shape issues,we can manipulate the shape of one of oue tensors using a **transpose**.
A **transpose** switches the axes or dimension of a given tensor.

In [ ]:
tensor_B,tensor_B.shape

In [ ]:
tensor_B.T,tensor_B.T.shape

In [103]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape:tensor_A={tensor_A.shape},tensor_B = {tensor_B.shape}")
print(f"New shapes:tensor_A = {tensor_A.shape} (same shape as above),tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A,tensor_B.T)

Original shape:tensor_A=torch.Size([3, 2]),tensor_B = torch.Size([3, 2])
New shapes:tensor_A = torch.Size([3, 2]) (same shape as above),tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  30,  33],
        [ 53,  68,  75],
        [ 83, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 23,  30,  33],
        [ 53,  68,  75],
        [ 83, 106, 117]])

## Finding the min,max,mean,sum,ect(tensor aggregation)

In [104]:
# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [105]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [106]:
# Find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [107]:
# Find the mean -note:the torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [108]:
# Find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [109]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [110]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmin()

tensor(0)

In [111]:
x[0]

tensor(1)

In [112]:
x[9]

tensor(91)

## Reshaping,stacking,squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View-Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking-combine multiple tensors onn top of each other(vstack) or side by side(hstack)
* Squeeze-removes all 1 dimensions from a tensor
* Unsqueeze-add a 1 demension to a target tensor
* Permute-Return a view of the input with dimensions permuted(swapped) in certain way

In [115]:
# Let't create a tensor
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [116]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [117]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [118]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [119]:
# Change the view
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [120]:
# Changing z changes x (because a view of a tensor shares the same memory as the original inpu)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [121]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [122]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [130]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [131]:
# torch.unsqueeze() - adds a single diimension to a taget tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [132]:
# torch.unsqueeze() - adds a single diimension to a taget tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [125]:
x_reshaped.shape

torch.Size([1, 9])

In [126]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [127]:
x_reshaped.squeeze().shape

torch.Size([9])

In [133]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(244,244,3)) #[height,width,colour_channels]

# Permute the original tensor to rearrange the axis （or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels,height,width]

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


In [142]:
x_original[0, 0, 0]

tensor(728718.)