<a href="https://colab.research.google.com/github/annala999/Pytorch-Tutorial-Youtube/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


# Introduction to Tensors
## Creating tensors
#### PyTorch tensors are created torch.Tensor()=https:pytorch.org/docs/stable/tensor.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors
### Why random tensors?
#### Random tensor are important because the way many networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
##### Start with random numbers -> look at data -> updata random numbers -> look at data -> updata random *numbers*

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7092, 0.1694, 0.5047, 0.0811],
        [0.5036, 0.9177, 0.5191, 0.3463],
        [0.0129, 0.9851, 0.5564, 0.6818]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,244,244)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [18]:
random_image_size_tensor = torch.rand(size=(244,244,3)) #height,width,color channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and omes

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

## Creating a range of tensors and tensor-like

In [23]:
# Use torch.range() and deprecated message,use torch.arange()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device


In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,   #What datatype is the tensor (e.g. float32 or float16)
                               device=None,  # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [27]:
non_default_tensor = torch.tensor([3.0,6.0,9.0],
                                  dtype=torch.float16)
non_default_tensor,non_default_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor


tensor([3, 6, 9])

In [33]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### Getting information from tensors ( tensor attributes)
1.Tensors not right datatype - to do get datatype from a tensor,can use tensor.dtype

2.Tensors not right shape - to get shape from a tensor,can use tensor.shape

3.Tensors not on the right device - to get device from a tensor,can use tensor.device

In [34]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9103, 0.2437, 0.7845, 0.9353],
        [0.5855, 0.3048, 0.0662, 0.5849],
        [0.7958, 0.4048, 0.3490, 0.9075]])

In [35]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [36]:
some_tensor.size

<function Tensor.size>

In [38]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.9103, 0.2437, 0.7845, 0.9353],
        [0.5855, 0.3048, 0.0662, 0.5849],
        [0.7958, 0.4048, 0.3490, 0.9075]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


## Manipulating Tensors(tensor operations)
Tensor opertions include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [41]:
# Creat a tensor and 10 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [42]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
# Substract 10
tensor-10

tensor([-9, -8, -7])

In [45]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [46]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:

   1.Element-wise multiplication

   2.Matrix mutliplication(dot product)

In [47]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [49]:
tensor

tensor([1, 2, 3])

In [50]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.11 ms, sys: 0 ns, total: 2.11 ms
Wall time: 8.19 ms


In [52]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 947 µs, sys: 0 ns, total: 947 µs
Wall time: 1.55 ms


tensor(14)